Update HA-Lambda-WP_configuration.yaml
RalfWinter/lambda-heatpump-modbus-tcp-HA pull request #2
Opened 2023-05-16 16:16 UTC by thecem

correctetd state_class and added device_class:

https://developers.home-assistant.io/docs/core/entity/sensor/

https://www.home-assistant.io/integrations/sensor/

2024-07-25 07:45 UTC, SamuelBrucksch commented on HA-Lambda-WP_configuration.yaml
> +          device_class: temeperature
typo

2024-07-25 07:45 UTC, SamuelBrucksch requested changes

2024-07-25 07:45 UTC, SamuelBrucksch commented on HA-Lambda-WP_configuration.yaml
> +          device_class: temeperature
typo, 25 occurences in total

2024-07-25 07:53 UTC, SamuelBrucksch commented on HA-Lambda-WP_configuration.yaml
> +          state_class: measurement
```suggestion
          state_class: measurement
          device_class: temperature
```

same for other temp values around here

2024-07-27 09:09 UTC, RalfWinter commented on HA-Lambda-WP_configuration.yaml
> +          state_class: measurement
I applied your changes, but not the typos ;-)

2025-02-18 17:44 UTC, RalfWinter commented
Changes went into the original code. Thanks!

2025-02-18 17:44 UTC, closed without merging